
export const NOTIFY_USER = 'NOTIFY_USER';
export const DISABALE_BALANCE_ON_ADD = 'DISABALE_BALANCE_ON_ADD';
export const DISABALE_BALANCE_ON_EDIT = 'DISABALE_BALANCE_ON_EDIT';
export const ALLOW_REGISTRATION = 'ALLOW_REGISTRATION';


